export const UserActionTypes = {
	SET_CURRENT_USER: 'SET_CURRENT_USER',
	SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
	SIGN_IN_FALIURE: 'SIGN_IN_FALIURE',
	SIGN_OUT_START: 'SIGN_OUT_START',
	SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
	SIGN_OUT_FALIURE: 'SIGN_OUT_FALIURE',
	SIGN_UP_START: 'SIGN_UP_START',
	SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
	SIGN_UP_FALIURE: 'SIGN_UP_FALIURE',
	CHECK_USER_SESSION: 'CHECK_USER_SESSION',
};
